// <auto-generated />
using System;
using Domain.DataLayer.Contexts.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(AppBaseDbContex))]
    [Migration("20240412181503_AddedFileServer")]
    partial class AddedFileServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.TblChatRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ChatRoomTitle")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("MyChatId")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProfileImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("MyChatId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProfileImageId");

                    b.ToTable("TblChatRoom");
                });

            modelBuilder.Entity("Domain.Entities.TblFileServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex(new[] { "Title" }, "IX_TTblFileServer_Title")
                        .IsUnique();

                    b.ToTable("TblFileServer");
                });

            modelBuilder.Entity("Domain.Entities.TblImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("TblImage");
                });

            modelBuilder.Entity("Domain.Entities.TblMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FileMimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FileServerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("FileServerId");

                    b.HasIndex("MessageId");

                    b.HasIndex("ModifiedById");

                    b.ToTable("TblMedia");
                });

            modelBuilder.Entity("Domain.Entities.TblMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFromSystem")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("RecieverChatRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ReplyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("RecieverChatRoomId");

                    b.HasIndex("ReplyId");

                    b.ToTable("TblMessage");
                });

            modelBuilder.Entity("Domain.Entities.TblMyChatIdentifier", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Identifier");

                    b.ToTable("TblMyChatIdentifier");
                });

            modelBuilder.Entity("Domain.Entities.TblPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("TblPermission");
                });

            modelBuilder.Entity("Domain.Entities.TblRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsCostume")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("TblRole");
                });

            modelBuilder.Entity("Domain.Entities.TblRolePermissionRel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("TblRolePermissionRel");
                });

            modelBuilder.Entity("Domain.Entities.TblSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("ShowLastSeen")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowOnline")
                        .HasColumnType("bit");

                    b.Property<short>("ShowPhoneNumber")
                        .HasColumnType("smallint")
                        .HasComment("0 NoBody\r\n1 MyContacts\r\n2 EveryBody\r\n");

                    b.Property<bool>("ShowProfilePhoto")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("TblSetting");
                });

            modelBuilder.Entity("Domain.Entities.TblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<string>("Bio")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateSigned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("LastOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("ProfileImageUrl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("4c271239-f0c1-ee11-b6e1-44af2843979e"));

                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValue(new Guid("62af09e2-6af8-ee11-b6e5-44af284397a1"));

                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Tell")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileImageUrl");

                    b.HasIndex("RoleId");

                    b.HasIndex("SettingId");

                    b.HasIndex("UserName");

                    b.HasIndex(new[] { "Tell" }, "IX_TblUsers_Tell")
                        .IsUnique();

                    b.ToTable("TblUser");
                });

            modelBuilder.Entity("Domain.Entities.TblUserChatRoomRel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("ChatRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastSeenMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("LastSeenMessageId");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("UserId");

                    b.ToTable("TblUserChatRoomRel");
                });

            modelBuilder.Entity("Domain.Entities.TblUserContacts", b =>
                {
                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("ContactUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CreatedById", "ContactName");

                    b.HasIndex("ContactUserId");

                    b.HasIndex("ModifiedById");

                    b.ToTable("TblUserContacts");
                });

            modelBuilder.Entity("Domain.Entities.TblUserImageRel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid?>("DeleteById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ImageUrl")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeleteById");

                    b.HasIndex("ImageUrl");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("UserId");

                    b.ToTable("TblUserImageRel");
                });

            modelBuilder.Entity("Domain.Entities.TblChatRoom", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany("TblChatRooms")
                        .HasForeignKey("CreatedById")
                        .IsRequired()
                        .HasConstraintName("FK_TblChatRoom_TblUsers");

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblMyChatIdentifier", "MyChat")
                        .WithMany("TblChatRooms")
                        .HasForeignKey("MyChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_TblChatRoom_TblMyChatIdentifier");

                    b.HasOne("Domain.Entities.TblChatRoom", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_TblChatRoom_TblChatRoom");

                    b.HasOne("Domain.Entities.TblImage", "ProfileImage")
                        .WithMany("TblChatRooms")
                        .HasForeignKey("ProfileImageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_TblChatRoom_TblImage");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("MyChat");

                    b.Navigation("Parent");

                    b.Navigation("ProfileImage");
                });

            modelBuilder.Entity("Domain.Entities.TblFileServer", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Domain.Entities.TblImage", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Domain.Entities.TblMedia", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblFileServer", "FileServer")
                        .WithMany("TblMedias")
                        .HasForeignKey("FileServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBlMedia_TblFileServer");

                    b.HasOne("Domain.Entities.TblMessage", "Message")
                        .WithMany("TblMedias")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TblMedia_TblMessage");

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("FileServer");

                    b.Navigation("Message");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Domain.Entities.TblMessage", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany("TblMessages")
                        .HasForeignKey("CreatedById")
                        .IsRequired()
                        .HasConstraintName("FK_TblMessage_TblUsers");

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblChatRoom", "RecieverChatRoom")
                        .WithMany("TblMessages")
                        .HasForeignKey("RecieverChatRoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TblMessage_TblChatRoom");

                    b.HasOne("Domain.Entities.TblMessage", "Reply")
                        .WithMany("InverseReplys")
                        .HasForeignKey("ReplyId")
                        .HasConstraintName("FK_TblMessage_TblMessage");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("RecieverChatRoom");

                    b.Navigation("Reply");
                });

            modelBuilder.Entity("Domain.Entities.TblPermission", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Domain.Entities.TblRole", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Domain.Entities.TblRolePermissionRel", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblPermission", "Permission")
                        .WithMany("TblRolePermissionRels")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TblRolePermissionRel_TblPermission");

                    b.HasOne("Domain.Entities.TblRole", "Role")
                        .WithMany("TblRolePermissionRels")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TblRolePermissionRel_TblRole");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.TblSetting", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Domain.Entities.TblUser", b =>
                {
                    b.HasOne("Domain.Entities.TblImage", "ProfileImageUrlNavigation")
                        .WithMany("TblUsers")
                        .HasForeignKey("ProfileImageUrl")
                        .IsRequired()
                        .HasConstraintName("FK_TblUsers_TblImage");

                    b.HasOne("Domain.Entities.TblRole", "Role")
                        .WithMany("TblUsers")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_TblUsers_TblRole");

                    b.HasOne("Domain.Entities.TblSetting", "Setting")
                        .WithMany("TblUsers")
                        .HasForeignKey("SettingId")
                        .IsRequired()
                        .HasConstraintName("FK_TblUsers_TblSettings");

                    b.HasOne("Domain.Entities.TblMyChatIdentifier", "UserNameNavigation")
                        .WithMany("TblUsers")
                        .HasForeignKey("UserName")
                        .IsRequired()
                        .HasConstraintName("FK_TblUsers_TblMyChatIdentifier");

                    b.Navigation("ProfileImageUrlNavigation");

                    b.Navigation("Role");

                    b.Navigation("Setting");

                    b.Navigation("UserNameNavigation");
                });

            modelBuilder.Entity("Domain.Entities.TblUserChatRoomRel", b =>
                {
                    b.HasOne("Domain.Entities.TblChatRoom", "ChatRoom")
                        .WithMany("TblUserChatRoomRels")
                        .HasForeignKey("ChatRoomId")
                        .IsRequired()
                        .HasConstraintName("FK_TblUserChatRoomRel_TblChatRoom");

                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblMessage", "LastSeenMessage")
                        .WithMany("ReadedBys")
                        .HasForeignKey("LastSeenMessageId");

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblUser", "User")
                        .WithMany("TblUserChatRoomRels")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TblUserChatRoomRel_TblUsers");

                    b.Navigation("ChatRoom");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("LastSeenMessage");

                    b.Navigation("ModifiedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.TblUserContacts", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "ContactUser")
                        .WithMany("TblUserContactsContactUsers")
                        .HasForeignKey("ContactUserId")
                        .IsRequired()
                        .HasConstraintName("FK_TblUserContacts_TblUsers1");

                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany("TblUserContactsContactListCreateds")
                        .HasForeignKey("CreatedById")
                        .IsRequired()
                        .HasConstraintName("FK_TblUserContacts_TblUsers");

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.Navigation("ContactUser");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Domain.Entities.TblUserImageRel", b =>
                {
                    b.HasOne("Domain.Entities.TblUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TblUser", "DeleteBy")
                        .WithMany()
                        .HasForeignKey("DeleteById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblImage", "ImageUrlNavigation")
                        .WithMany("TblUserImageRels")
                        .HasForeignKey("ImageUrl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TblUserImageRel_TblImage");

                    b.HasOne("Domain.Entities.TblUser", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.TblUser", "User")
                        .WithMany("TblUserImageRels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TblUserImageRel_TblUsers");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeleteBy");

                    b.Navigation("ImageUrlNavigation");

                    b.Navigation("ModifiedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.TblChatRoom", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("TblMessages");

                    b.Navigation("TblUserChatRoomRels");
                });

            modelBuilder.Entity("Domain.Entities.TblFileServer", b =>
                {
                    b.Navigation("TblMedias");
                });

            modelBuilder.Entity("Domain.Entities.TblImage", b =>
                {
                    b.Navigation("TblChatRooms");

                    b.Navigation("TblUserImageRels");

                    b.Navigation("TblUsers");
                });

            modelBuilder.Entity("Domain.Entities.TblMessage", b =>
                {
                    b.Navigation("InverseReplys");

                    b.Navigation("ReadedBys");

                    b.Navigation("TblMedias");
                });

            modelBuilder.Entity("Domain.Entities.TblMyChatIdentifier", b =>
                {
                    b.Navigation("TblChatRooms");

                    b.Navigation("TblUsers");
                });

            modelBuilder.Entity("Domain.Entities.TblPermission", b =>
                {
                    b.Navigation("TblRolePermissionRels");
                });

            modelBuilder.Entity("Domain.Entities.TblRole", b =>
                {
                    b.Navigation("TblRolePermissionRels");

                    b.Navigation("TblUsers");
                });

            modelBuilder.Entity("Domain.Entities.TblSetting", b =>
                {
                    b.Navigation("TblUsers");
                });

            modelBuilder.Entity("Domain.Entities.TblUser", b =>
                {
                    b.Navigation("TblChatRooms");

                    b.Navigation("TblMessages");

                    b.Navigation("TblUserChatRoomRels");

                    b.Navigation("TblUserContactsContactListCreateds");

                    b.Navigation("TblUserContactsContactUsers");

                    b.Navigation("TblUserImageRels");
                });
#pragma warning restore 612, 618
        }
    }
}
